name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - 'fix/*'
      - '*'

jobs:
  build: # make sure build/ci work properly
    strategy:
      fail-fast: false
      matrix:
        xcode: ['xcode16', 'xcode15']
        include:
          - xcode: 'xcode16'
            xcode-path: '/Applications/Xcode_16.0.app'
            macos: 'macos-15'
          - xcode: 'xcode15'
            xcode-path: '/Applications/Xcode_15.4.app'
            macos: 'macos-14'
    runs-on: ${{ matrix.macos }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    strategy:
      fail-fast: false
      matrix:
        xcode: ['xcode16', 'xcode15']
        include:
          - xcode: 'xcode16'
            xcode-path: '/Applications/Xcode_16.0.app'
            macos: 'macos-15'
          - xcode: 'xcode15'
            xcode-path: '/Applications/Xcode_15.4.app'
            macos: 'macos-14'
    runs-on: ${{ matrix.macos }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          path: __tests__/data/Example.xcresult
          title: 'Example test report (${{ matrix.xcode }})'
      - uses: ./
        with:
          path: __tests__/data/Example.xcresult
          title: 'Example Failures Only test report (${{ matrix.xcode }})'
          show-passed-tests: false
      - uses: ./
        with:
          path: __tests__/data/KeychainAccess.xcresult
          title: 'KeychainAccess Failures Only test report (${{ matrix.xcode }})'
          show-passed-tests: false
      - uses: ./
        with:
          path: __tests__/data/KeychainAccess.xcresult
          title: 'KeychainAccess test report (${{ matrix.xcode }})'
      - uses: ./
        with:
          path: __tests__/data/TAU.xcresult
          title: 'TAU test report (${{ matrix.xcode }})'
      - uses: ./
        with:
          path: __tests__/data/TestResults.xcresult
          title: 'TestResults test report (${{ matrix.xcode }})'
      - uses: ./
        with:
          path: __tests__/data/Coverage.xcresult
          title: 'Coverage test report (${{ matrix.xcode }})'
      - uses: ./
        with:
          path: __tests__/data/Coverage.xcresult
          title: 'Hide Coverage test report (${{ matrix.xcode }})'
          show-code-coverage: false
      - uses: ./
        with:
          path: __tests__/data/UhooiPicBook.xcresult
          title: 'UhooiPicBook test report (${{ matrix.xcode }})'
      - uses: ./
        with:
          path: __tests__/data/UhooiPicBook.xcresult
          title: 'UhooiPicBook No Passed test report (${{ matrix.xcode }})'
          show-passed-tests: false
      - uses: ./
        with:
          path: __tests__/data/UhooiPicBook.xcresult
          title: 'UhooiPicBook No Code Coverage test report (${{ matrix.xcode }})'
          show-code-coverage: false
      - uses: ./
        with:
          path: |
            __tests__/data/Example.xcresult
            __tests__/data/KeychainAccess.xcresult
            __tests__/data/TAU.xcresult
          title: 'Multiple Paths (${{ matrix.xcode }})'
